export async function onRequest(context) {
  const db = context.env.DB;
  try {
    const s = [];
    s.push(`CREATE TABLE IF NOT EXISTS guitar_modules (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      tier TEXT NOT NULL CHECK(tier IN ('bronze','silver','gold')),
      title TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, subtitle TEXT DEFAULT '',
      description TEXT NOT NULL DEFAULT '', image TEXT DEFAULT '',
      sort_order INTEGER NOT NULL DEFAULT 0, lesson_count INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_lessons (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      module_id INTEGER NOT NULL, title TEXT NOT NULL, slug TEXT NOT NULL,
      sort_order INTEGER DEFAULT 0, content_html TEXT DEFAULT '',
      youtube_url TEXT DEFAULT '', duration_min INTEGER DEFAULT 5,
      practice_type TEXT DEFAULT '', practice_config TEXT DEFAULT '{}',
      FOREIGN KEY (module_id) REFERENCES guitar_modules(id)
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_exercises (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      lesson_id INTEGER NOT NULL, type TEXT NOT NULL,
      title TEXT NOT NULL, description TEXT DEFAULT '',
      config TEXT DEFAULT '{}', sort_order INTEGER DEFAULT 0,
      FOREIGN KEY (lesson_id) REFERENCES guitar_lessons(id)
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_songs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL, artist TEXT NOT NULL, genre TEXT DEFAULT 'Highlife',
      chords TEXT NOT NULL, difficulty INTEGER DEFAULT 1,
      min_module_id INTEGER DEFAULT 1, youtube_url TEXT DEFAULT '',
      chord_progression TEXT DEFAULT '', lyrics_preview TEXT DEFAULT '',
      image TEXT DEFAULT '', ghanaian INTEGER DEFAULT 1
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_achievements (
      key TEXT PRIMARY KEY, tier TEXT DEFAULT 'bronze',
      name TEXT NOT NULL, description TEXT DEFAULT '',
      icon TEXT DEFAULT '', criteria JSON DEFAULT '{}'
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_progress (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL, lesson_id INTEGER NOT NULL,
      completed INTEGER DEFAULT 0, xp INTEGER DEFAULT 0,
      completed_at TEXT DEFAULT '', updated_at TEXT DEFAULT (datetime('now')),
      FOREIGN KEY (user_id) REFERENCES users(id),
      UNIQUE(user_id, lesson_id)
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_practice_sessions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL, date TEXT NOT NULL,
      duration_min INTEGER DEFAULT 0, drill_type TEXT DEFAULT '',
      drill_config TEXT DEFAULT '{}', score INTEGER DEFAULT 0,
      xp_earned INTEGER DEFAULT 0, notes TEXT DEFAULT '',
      created_at TEXT DEFAULT (datetime('now')),
      FOREIGN KEY (user_id) REFERENCES users(id)
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_one_minute_records (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL, chord_pair TEXT NOT NULL,
      score INTEGER NOT NULL, achieved_at TEXT DEFAULT (datetime('now')),
      FOREIGN KEY (user_id) REFERENCES users(id)
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_user_stats (
      user_id INTEGER PRIMARY KEY, total_xp INTEGER DEFAULT 0,
      level INTEGER DEFAULT 1, streak INTEGER DEFAULT 0,
      last_practice_date TEXT DEFAULT '', total_practice_min INTEGER DEFAULT 0,
      total_sessions INTEGER DEFAULT 0, songs_mastered INTEGER DEFAULT 0,
      perfect_drills INTEGER DEFAULT 0, updated_at TEXT DEFAULT (datetime('now')),
      FOREIGN KEY (user_id) REFERENCES users(id)
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_user_achievements (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL, achievement_key TEXT NOT NULL,
      earned_at TEXT DEFAULT (datetime('now')),
      FOREIGN KEY (user_id) REFERENCES users(id),
      UNIQUE(user_id, achievement_key)
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_payments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL, email TEXT NOT NULL,
      status TEXT DEFAULT 'pending', flw_tx_ref TEXT DEFAULT '',
      amount REAL DEFAULT 250, currency TEXT DEFAULT 'GHS',
      plan TEXT DEFAULT 'full', created_at TEXT DEFAULT (datetime('now'))
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_tuner_history (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER DEFAULT 0, note_detected TEXT DEFAULT '',
      cents_off REAL DEFAULT 0, string_num INTEGER DEFAULT 0,
      created_at TEXT DEFAULT (datetime('now'))
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_waitlist (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL, name TEXT NOT NULL,
      email TEXT NOT NULL, phone TEXT DEFAULT '',
      skill_level TEXT DEFAULT 'beginner',
      registered_at TEXT DEFAULT (datetime('now')),
      brevo_id TEXT DEFAULT '',
      FOREIGN KEY (user_id) REFERENCES users(id)
    )`);
    s.push(`CREATE TABLE IF NOT EXISTS guitar_conversion_events (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER DEFAULT NULL,
      event_type TEXT NOT NULL,
      page_url TEXT DEFAULT '',
      source TEXT DEFAULT '',
      metadata TEXT DEFAULT '{}',
      ip_address TEXT DEFAULT '',
      user_agent TEXT DEFAULT '',
      created_at TEXT DEFAULT (datetime('now'))
    )`);
    for (const sql of s) { try { await db.prepare(sql).run(); } catch(e) { console.error('Schema:', e.message); } }

    const seeds = [];
    seeds.push(`DELETE FROM guitar_modules`);
    seeds.push(`INSERT OR IGNORE INTO guitar_modules (tier,title,slug,subtitle,description,sort_order,lesson_count) VALUES
      ('bronze','Meet Your Guitar','meet-your-guitar','Parts, Tuning & Posture','Learn the parts of the guitar, how to hold it properly, and how to tune it by ear and with a tuner.',1,4),
      ('bronze','The Fretboard','the-fretboard','Strings, Notes & Finger Independence','Memorise the open string names and start building finger independence with fretboard crawls.',2,4),
      ('bronze','The Power 5 Chords','power-5-chords','Em • Am • G • C • D','Learn the five chords that unlock 80% of popular music. Master clean shapes and smooth transitions.',3,4),
      ('bronze','Rhythm Foundation','rhythm-foundation','Strumming & Time Keeping','Develop your sense of rhythm with down-strumming, the metronome, and basic time signatures.',4,4),
      ('bronze','One-Minute Changes','one-minute-changes','Speed & Accuracy Drill','The single most effective beginner drill. Track your chord change speed and watch it improve daily.',5,4),
      ('silver','Your First Song','your-first-song','2-Chord Song in Ghanaian Style','Play your first complete song using just two chords. Feel the joy of making real music.',6,4),
      ('silver','Strumming Patterns','strumming-patterns','Down-Up • Syncopation • Feel','Expand your rhythmic vocabulary with essential strumming patterns used in highlife, gospel and hiplife.',7,4),
      ('silver','More Chords','more-chords','A • E • Dm • B7 • F (partial)','Add five more chords to your toolkit and learn tricks for smooth transitions between any chord pair.',8,4),
      ('silver','Ghanaian Songcraft','ghanaian-songcraft','3-4 Chord Hits','Play real Ghanaian songs. Ayayi, Ewe, Adom and more — learn the progressions that define Ghanaian music.',9,4),
      ('silver','Reading Tablature','reading-tablature','Tabs • Notation • Finding Notes','Learn to read guitar tablature so you can learn any song from the internet.',10,4),
      ('silver','Pentatonic Foundation','pentatonic-foundation','First 5 Notes of Lead Guitar','Dive into the A minor pentatonic scale — the most used scale in guitar music. Your first step to soloing.',11,4),
      ('gold','Fingerpicking','fingerpicking','Thumb-Lead Patterns & Folk Melodies','Develop fingerstyle technique with thumb-lead patterns and Ghanaian folk-inspired melodies.',12,4),
      ('gold','The Barre Wall','barre-wall','F • Bm • Partial & Full Shapes','The #1 reason guitarists quit. We''ll break barre chords down into manageable steps and build strength gradually.',13,4),
      ('gold','Ghanaian Lead Guitar','ghanaian-lead','Highlife Guitar Phrasing','Learn the signature highlife guitar style — the chicken-pick, the chop, and the fluid phrasing of Ebo Taylor and Amakye Dede.',14,4),
      ('gold','Song Mastery Project','song-mastery','Learn & Perform One Complete Song','Choose a song, learn every part, and record your first performance. Certificate eligible.',15,4),
      ('gold','Performance Mode','performance-mode','Play-Along with Scoring','Put it all together in a scored play-along session with real-time pitch detection and accuracy tracking.',16,4)`);

    seeds.push(`DELETE FROM guitar_lessons`);
    seeds.push(`INSERT INTO guitar_lessons (module_id,title,slug,sort_order,content_html,youtube_url,duration_min,practice_type,practice_config) VALUES
      (1,'Parts of the Guitar','parts-of-guitar',1,'<p>The guitar has three main sections: the <strong>headstock</strong> (top), the <strong>neck</strong> (middle), and the <strong>body</strong> (bottom).</p><ul><li><strong>Headstock</strong> — holds the tuning pegs. Turn them to tighten or loosen strings.</li><li><strong>Nut</strong> — the small white slot where strings rest before the tuning pegs.</li><li><strong>Frets</strong> — the metal strips on the neck. Pressing a string behind a fret changes its pitch.</li><li><strong>Soundhole</strong> (acoustic) or <strong>pickups</strong> (electric) — where the sound comes out.</li><li><strong>Bridge</strong> — holds the strings at the body end.</li></ul><p>Spend 2 minutes identifying each part on your actual guitar. Touch each part as you read its name — this builds physical memory.</p>','https://www.youtube.com/embed/4WUlLx6a9BU',5,'none','{}'),
      (1,'How to Hold the Guitar','how-to-hold',2,'<p>Good posture prevents injury and makes playing easier.</p><p><strong>Sitting position:</strong> Sit on the edge of a chair. Rest the guitar on your picking-leg thigh. The neck points upward at about 45°. Keep your back straight — don''t hunch over to look at the fretboard.</p><p><strong>Standing position:</strong> Adjust your strap so the guitar sits at the same height as when sitting. The neck should still point up.</p><p><strong>Left hand (fretting):</strong> Your thumb rests on the back of the neck, opposite your index finger. Curl your fingers so the tips press the strings — not the pads.</p><p><strong>Right hand (picking):</strong> Rest your forearm lightly on the guitar body. Keep your wrist relaxed, not locked.</p><p>Practice holding the guitar for 2 minutes while watching yourself in a mirror. Adjust until it feels natural.</p>','https://www.youtube.com/embed/6YNWkR7mh4Y',5,'none','{}'),
      (1,'How to Tune Your Guitar','tuning',3,'<p>A guitar that''s out of tune sounds bad no matter how well you play. Tuning is a non-negotiable habit.</p><p><strong>Standard tuning (EADGBe):</strong></p><ul><li>String 6 (thickest) — E</li><li>String 5 — A</li><li>String 4 — D</li><li>String 3 — G</li><li>String 2 — B</li><li>String 1 (thinnest) — e</li></ul><p>Mnemonic: <strong>E</strong>ddie <strong>A</strong>te <strong>D</strong>ynamite <strong>G</strong>ood <strong>B</strong>ye <strong>E</strong>ddie</p><p><strong>Using our built-in tuner:</strong> Open the Tuner page, play each string, and watch the needle. Turn the tuning peg until the needle centres on the correct note.</p><p><strong>Relative tuning (no tuner):</strong> Press the 5th fret on string 6 — that''s an A, matching the open string 5. Use this method to tune all strings relative to string 6.</p><p>Practice tuning your guitar twice: once with the tuner, once by ear. This builds your ear muscles.</p>','https://www.youtube.com/embed/xcmUReUJhpM',8,'tuner','{}'),
      (1,'Posture & Ergonomics Check','posture-check',4,'<p>Do a full body scan while holding your guitar:</p><ul><li><strong>Shoulders:</strong> Relaxed, not hunched</li><li><strong>Wrists:</strong> Straight, not bent sharply</li><li><strong>Fingers:</strong> Curled, tips on strings</li><li><strong>Back:</strong> Straight, leaning slightly forward from the hips</li><li><strong>Feet:</strong> Flat on the floor (use a foot stool if one leg is higher)</li></ul><p><strong>The 2-minute challenge:</strong> Play open string 1 (high e) repeatedly for 2 minutes while maintaining perfect posture. Stop and reset any time you notice tension. This teaches you to practice WITH your body, not against it.</p>','https://www.youtube.com/embed/01gRTiVyBQ0',4,'posture','{"blocks":2,"block_type":"posture_check"}'),
      (2,'Open String Names','open-string-names',1,'<p>Your guitar has 6 strings, each with a name and a number.</p><p><strong>From thickest to thinnest:</strong></p><table><tr><th>String</th><th>Note</th><th>Number</th><th>Memory Aid</th></tr><tr><td>6th (thickest)</td><td>E</td><td>6</td><td>Eddie</td></tr><tr><td>5th</td><td>A</td><td>5</td><td>Ate</td></tr><tr><td>4th</td><td>D</td><td>4</td><td>Dynamite</td></tr><tr><td>3rd</td><td>G</td><td>3</td><td>Good</td></tr><tr><td>2nd</td><td>B</td><td>2</td><td>Bye</td></tr><tr><td>1st (thinnest)</td><td>E (high)</td><td>1</td><td>Eddie</td></tr></table><p><strong>Drill:</strong> Without looking at the table, name each string from thickest to thinnest. Then from thinnest to thickest. Do this 5 times.</p>','https://www.youtube.com/embed/9Z6UkC3ebFc',5,'fretboard','{"mode":"string_names"}'),
      (2,'Finger Independence Exercises','finger-independence',2,'<p>Your ring and pinky fingers share a tendon — they naturally want to move together. These exercises train them to work independently.</p><p><strong>Exercise 1: The Spider Walk</strong></p><p>Place all 4 fingers on string 6, one per fret (index=1, middle=2, ring=3, pinky=4). Play each finger one at a time. Move to string 5 and repeat. Go across all 6 strings.</p><p><strong>Exercise 2: Fretboard Crawl (Recommended)</strong></p><ol><li>Index finger on string 6, fret 1. Play it.</li><li>Middle finger on string 6, fret 2. Play it — don''t lift the index!</li><li>Ring finger on fret 3. Play it.</li><li>Pinky on fret 4. Play it.</li><li>Move to string 5 and repeat from fret 1.</li><li>Go all the way to string 1, then crawl back.</li></ol><p>Start at 60 BPM. Only move up when every note rings cleanly.</p>','https://www.youtube.com/embed/fZ9uHWoP2r8',8,'fretboard','{"mode":"spider_walk","bpm":60}'),
      (2,'Natural Notes on the Fretboard','natural-notes',3,'<p>The musical alphabet uses only 7 letters: A B C D E F G. After G, it loops back to A.</p><p><strong>Natural notes on the guitar:</strong> Each fret moves up one semitone (half-step). The natural notes (no sharps/flats) on string 6 (E):</p><p>Open=E, Fret 1=F, Fret 3=G, Fret 5=A, Fret 7=B, Fret 8=C, Fret 10=D, Fret 12=E (octave)</p><p><strong>Key rule:</strong> B→C and E→F are always 1 fret apart (no sharp/flat in between). All other natural notes are 2 frets apart.</p><p>Learn the natural notes on string 6 and string 1 first (they''re both E strings, so the notes are identical). Then move to string 5 (A).</p>','https://www.youtube.com/embed/xl5Mcd0xCPQ',8,'fretboard','{"mode":"note_memory"}'),
      (2,'Fretboard Quiz','fretboard-quiz',4,'<p>Time to test yourself. <strong>Active recall</strong> — trying to remember rather than looking — is scientifically proven to build stronger memory than passive review.</p><p>Cover the diagram below. For each string number, name the note at the given fret:</p><ul><li>String 6, Fret 3 → _____</li><li>String 5, Fret 5 → _____</li><li>String 4, Fret 2 → _____</li><li>String 3, Fret 0 (open) → _____</li><li>String 2, Fret 1 → _____</li><li>String 1, Fret 5 → _____</li></ul><p>Answers: G, D, E, G, C, A. If you got 4+ right, great! If less than 4, review the previous lesson and try again tomorrow. Spaced repetition means you''ll remember more each time.</p>','https://www.youtube.com/embed/UKjRwDapGhs',5,'fretboard','{"mode":"quiz"}'),
      (3,'Em — The Easiest Chord','em-chord',1,'<p><strong>Em (E minor)</strong> is the first chord every beginner should learn. It only uses 2 fingers!</p><p><strong>Shape:</strong></p><ul><li>Middle finger: String 5, Fret 2</li><li>Ring finger: String 4, Fret 2</li><li>Play all 6 strings</li></ul><p><strong>Checklist for a clean Em:</strong></p><ul><li>Are your fingertips pressing — not the pads?</li><li>Are your knuckles curved like you''re holding an apple?</li><li>Does every string ring clearly when you strum?</li></ul><p>Strum all 6 strings slowly. If a string buzzes, adjust that finger. Spend 3 minutes playing Em → mute with palm → Em → mute. This builds muscle memory.</p>','https://www.youtube.com/embed/PKB-p8UpC9I',6,'chord','{"chord":"Em","frets":[0,2,2,0,0,0]}'),
      (3,'Am — Your Second Chord','am-chord',2,'<p><strong>Am (A minor)</strong> — similar to Em but with a different root.</p><p><strong>Shape:</strong></p><ul><li>Index finger: String 2, Fret 1</li><li>Middle finger: String 4, Fret 2</li><li>Ring finger: String 3, Fret 2</li><li>Play only strings 1-5. DO NOT play string 6.</li></ul><p><strong>Practice switching Em ↔ Am:</strong></p><p>This is your first chord change. Em uses strings 5+4 at fret 2. Am uses strings 4+3 at fret 2 + string 2 at fret 1. The middle finger stays on fret 2 — it just moves from string 5 to string 4.</p><p>Set a timer for 1 minute. Count how many clean Em↔Am switches you can make. Write the number down.</p>','https://www.youtube.com/embed/IQrbbnn8EHM',6,'chord','{"chord":"Am","frets":[0,1,2,2,0,0]}'),
      (3,'G + C + D — The Big Three','big-three',3,'<p>These three chords (G, C, D) together with Em and Am unlock hundreds of songs.</p><p><strong>G major:</strong> Ring finger string 6 fret 3, middle string 5 fret 2, pinky string 1 fret 3, index string 5 fret 2 (barre). Or the simpler version: middle string 5 fret 2, index string 1 fret 2, ring string 6 fret 3, pinky string 2 fret 3.</p><p><strong>C major:</strong> Ring finger string 5 fret 3, middle string 4 fret 2, index string 2 fret 1. Don''t play string 6.</p><p><strong>D major:</strong> Index string 3 fret 2, middle string 1 fret 2, ring string 2 fret 3. Don''t play strings 5+6.</p><p><strong>Pro tip:</strong> When switching between G, C and D, keep your anchor fingers down. For G→C, your ring finger stays on string 5 fret 3 — it''s already in position for C.</p>','https://www.youtube.com/embed/gL6uG79dRG4',10,'chord','{"chords":["G","C","D"],"mode":"transition"}'),
      (3,'Chord Change Bootcamp','chord-change-bootcamp',4,'<p>This is the most important practice session of the entire course. <strong>One-Minute Changes</strong> is scientifically proven to build speed faster than any other drill.</p><p><strong>The drill:</strong></p><ol><li>Pick 2 chords (start with Em↔Am)</li><li>Set a timer for 60 seconds</li><li>Switch between them as fast as you can while keeping EVERY string clean</li><li>Count each successful switch (both chords clean)</li><li>Record your score</li></ol><p><strong>Your challenge:</strong> Repeat this drill 3 times per practice session. Your goal is 20+ clean changes in 60 seconds. Most beginners start at 8-12.</p><p><strong>Why this works:</strong> The timer creates urgency (activating your sympathetic nervous system), which speeds up motor learning. Tracking your score gives objective proof of improvement — the #1 motivator for continuing.</p>','https://www.youtube.com/embed/IaBmhFy1E6U',10,'oneminute','{"pairs":["Em-Am","Am-G","G-C","C-D","D-Em"],"target":20}'),
      (4,'Understanding Rhythm','understanding-rhythm',1,'<p>Rhythm is the backbone of music. Before you play chords, you need to feel the pulse.</p><p><strong>What is 4/4 time?</strong> Most music is in 4/4 — count "1, 2, 3, 4" and repeat. Each number is a <strong>beat</strong>.</p><p><strong>Exercise with your guitar:</strong></p><ol><li>Set our built-in metronome to 60 BPM (beats per minute)</li><li>Say "1, 2, 3, 4" out loud with each click</li><li>Tap your foot on beats 1 and 3</li><li>Strums the strings (muted with your left hand) on each click</li><li>Do this for 2 full minutes without stopping</li></ol><p>Your arm should move like a pendulum — down on the beat, up between beats. This is the foundation of all strumming.</p>','https://www.youtube.com/embed/I_7JwjiKF3c',6,'metronome','{"bpm":60,"pattern":"down_only"}'),
      (4,'Down-Only Strumming','down-strumming',2,'<p>Now apply rhythm to chords. We''ll use Em (your easiest chord) for all exercises.</p><p><strong>Down-strum only:</strong></p><ol><li>Metronome at 60 BPM</li><li>Hold Em chord</li><li>Strums ALL strings downward on each beat: 1, 2, 3, 4</li><li>Keep the strum smooth — don''t stab at the strings</li></ol><p><strong>The Pendulum Arm:</strong> Your strumming arm should swing continuously like a pendulum. The actual strum (string contact) happens at the bottom of the swing. The up-swing is silent for now.</p><p>Practice down-strums on Em for 3 minutes. Then try Am. Then try switching between them on each beat change (2 beats Em, 2 beats Am).</p>','https://www.youtube.com/embed/Ko52hf-eBNc',8,'metronome','{"bpm":60,"pattern":"down","chords":["Em","Am"]}'),
      (4,'The Metronome Challenge','metronome-challenge',3,'<p>Your metronome is your best friend. It doesn''t lie. If you''re not perfectly on time, you''ll hear it immediately.</p><p><strong>Challenge 1: Speed ramp</strong></p><ol><li>Start at 60 BPM — strum Em on every beat for 30 seconds</li><li>Increase to 80 BPM — 30 seconds</li><li>Increase to 100 BPM — 30 seconds</li><li>Decrease back to 60 BPM — notice how slow now feels EASY</li></ol><p><strong>Challenge 2: Accent beats</strong></p><p>Strum Em but play LOUDER on beat 1, softer on beats 2,3,4. This teaches dynamic control.</p><p><strong>Challenge 3: The silent beat</strong></p><p>Strum Em on beats 1, 2, 3 — rest on beat 4. Then rest on beats 2 and 4. This prepares you for real strumming patterns.</p>','https://www.youtube.com/embed/KYgphdFxw9Q',8,'metronome','{"bpm_range":[60,80,100],"chords":["Em","Am","G"]}'),
      (4,'Practice Session Structure','practice-structure',4,'<p>From now on, EVERY practice session follows this structure. It''s based on Ericsson''s deliberate practice research and has been proven to produce faster results than unstructured playing.</p><p><strong>The 20-Minute Session:</strong></p><table><tr><th>Block</th><th>Time</th><th>Activity</th></tr><tr><td>Warm-up</td><td>3 min</td><td>Spider walk or fretboard crawl</td></tr><tr><td>Technical Drill</td><td>5 min</td><td>One-minute changes on a chord pair</td></tr><tr><td>Song Practice</td><td>7 min</td><td>Play a song, focus on the hardest part</td></tr><tr><td>Free Play</td><td>5 min</td><td>Play whatever you enjoy</td></tr></table><p><strong>Golden rules:</strong></p><ul><li>Set a timer for each block — no block can steal time from another</li><li>80% of your session should feel slightly uncomfortable (that''s growth)</li><li>End with free play — this keeps you coming back</li></ul>','https://www.youtube.com/embed/mMpF50G9wME',4,'none','{}'),
      (5,'Em ↔ Am Speed Drill','em-am-speed',1,'<p>Your first One-Minute Changes target.</p><p><strong>Why Em↔Am first:</strong> Both are minor chords. The middle finger stays on fret 2 and only moves from string 5 (Em) to string 4 (Am). The ring finger just lifts and comes back down on string 3. Minimal movement = fastest improvement.</p><p><strong>Drill:</strong> 3 rounds of 60-second Em↔Am changes. Record your best score.</p><p><strong>Week 1 target:</strong> 15+ changes</p><p><strong>Week 2 target:</strong> 25+ changes</p><p><strong>Mastery:</strong> 35+ changes (pro level)</p>','https://www.youtube.com/embed/pH5nw0FQ30A',8,'oneminute','{"pair":"Em-Am"}'),
      (5,'Am ↔ G Speed Drill','am-g-speed',2,'<p>Now a bigger challenge — changing between Am and G. These shapes are very different, which means more finger movement.</p><p><strong>Am→G trick:</strong> In Am, your index is on string 2 fret 1. For G, lift all fingers and place them fresh. Don''t try to slide — just place all 3 fingers simultaneously.</p><p><strong>Drill:</strong> 3 rounds of 60-second Am↔G changes. Count clean transitions only.</p><p><strong>Target:</strong> 12+ changes</p>','https://www.youtube.com/embed/qwQvPSvdxb8',8,'oneminute','{"pair":"Am-G"}'),
      (5,'G ↔ C ↔ D Circuit','gcd-circuit',3,'<p>This is the most important chord progression in popular music — the I-IV-V progression in the key of G.</p><p><strong>The circuit:</strong> G → C → D → G → C → D → ... for 60 seconds</p><p><strong>Anchor finger technique:</strong></p><ul><li>G→C: Your ring finger stays on string 5 fret 3. Anchor it. Just move the other fingers.</li><li>C→D: Lift all fingers and place fresh. Keep D''s chord shape tight.</li><li>D→G: Lift and place all 3 fingers. The ring finger goes back to string 6 fret 3.</li></ul><p><strong>Drill:</strong> 3 rounds of 60 seconds. Count each complete G→C→D cycle.</p>','https://www.youtube.com/embed/WI63eA0S3a4',10,'oneminute','{"pairs":["G-C","C-D","D-G"]}'),
      (5,'One-Minute Championship','one-minute-championship',4,'<p>Time to put it all together. You''ll rotate through all your chord pairs.</p><p><strong>The gauntlet:</strong> 5 pairs, 60 seconds each, no rest between pairs.</p><ol><li>Em↔Am</li><li>Am↔G</li><li>G↔C</li><li>C↔D</li><li>D↔Em</li></ol><p>Record all 5 scores. Your "One-Minute Total" is the sum of all 5. Track this number daily.</p><p><strong>Beginner:</strong> 50+ total</p><p><strong>Intermediate:</strong> 80+ total</p><p><strong>Advanced:</strong> 120+ total</p><p>This ONE drill, done daily, will make you faster than 90% of self-taught guitarists within 3 months.</p>','https://www.youtube.com/embed/lkfFbr9XeLY',12,'oneminute','{"pairs":["Em-Am","Am-G","G-C","C-D","D-Em"]}'),
      (6,'2-Chord Songs Overview','2-chord-songs',1,'<p>The moment you''ve been waiting for — playing actual songs!</p><p>2-chord songs are the gateway to musical confidence. In Ghanaian music, many beautiful songs use just 2 chords repeated.</p><p><strong>How to practice a song:</strong></p><ol><li>Learn the chord progression WITHOUT strumming — just transition between the chords</li><li>Add a simple down-strum once transitions are smooth</li><li>Play along with the original recording at reduced speed (YouTube 0.75x)</li><li>Gradually speed up to full tempo</li></ol><p><strong>This week''s songs:</strong></p><ul><li>"Wish Me Well" by Sarkodie — Em ↔ Am (easiest!)</li><li>"Adonai" by Joe Mettle — G ↔ D</li><li>"Blessings" by Akwaboah — C ↔ G</li></ul>','https://www.youtube.com/embed/vErm6lJg8pQ',10,'song','{"songs":[1,2]}'),
      (6,'Wish Me Well — Sarkodie','wish-me-well',2,'<p><strong>Song:</strong> Wish Me Well — Sarkodie</p><p><strong>Chords:</strong> Em, Am (that''s it!)</p><p><strong>Progression:</strong> Em → Am → Em → Am (repeat)</p><p><strong>Strum pattern:</strong> Down, down-down-up (repeat)</p><p><strong>Lyrics (first verse):</strong></p><p><em>Wish me well, wish me well<br>Make I dey go my way<br>Wish me well, wish me well<br>I go make you proud one day</em></p><p><strong>Practice plan:</strong></p><ol><li>5 minutes: Em↔Am changes (no strum, just transitions)</li><li>5 minutes: strum Em 4 beats, switch to Am, strum 4 beats</li><li>5 minutes: play along with the YouTube video above</li></ol><p>By the end of this session, you should be able to play the first verse! This is your first real song. Celebrate this moment — it''s the beginning of your musical journey.</p>','https://www.youtube.com/embed/HnXo2LsYbMg',15,'song','{"song_id":1,"chords":["Em","Am"]}'),
      (6,'Playing with the Recording','play-along-song',3,'<p>Playing along with a recording is a skill in itself. Here''s how to do it effectively:</p><p><strong>Step 1:</strong> Find the tempo by tapping your foot to the song. Count "1, 2, 3, 4" in time.</p><p><strong>Step 2:</strong> Mute your strings with your left hand and strum the rhythm. Match your strum to the percussion.</p><p><strong>Step 3:</strong> Add the chords. Don''t worry about getting every transition perfect — aim for 80% right and keep going.</p><p><strong>Step 4:</strong> Loop a section you struggle with. YouTube has a loop feature (right click on video). Use it!</p><p><strong>Pro tip:</strong> Record yourself playing along with the song. Listen back. You''ll hear things you didn''t notice while playing — this is the fastest way to improve.</p>','https://www.youtube.com/embed/KxGSDsxG_JE',10,'song','{}'),
      (6,'Song Learning Method','song-learning-method',4,'<p>You now know a repeatable method for learning ANY song. Here''s the 5-step system:</p><ol><li><strong>Find the chords</strong> — search "[song name] chords" online</li><li><strong>Silent transitions</strong> — practice chord changes without strumming</li><li><strong>Slow play</strong> — strum once per chord change at half tempo</li><li><strong>Add rhythm</strong> — bring in the real strumming pattern</li><li><strong>Full tempo</strong> — play along with the recording</li></ol><p><strong>Your assignment:</strong> Use this method to learn ONE more 2-chord song of your choice this week. Any genre, any artist. The goal is not perfection — it''s completing the process.</p>','https://www.youtube.com/embed/ywJzvobXrx8',5,'song','{}'),
      (7,'Down-Up Strumming Pattern','down-up-strum',1,'<p>So far you''ve only strummed downward. Now we add the up-strum, which doubles your rhythmic possibilities.</p><p><strong>The Pendulum Arm (recap):</strong> Your arm swings down and up continuously. The hand brushes the strings at the bottom of the swing (down) and at the top of the swing (up).</p><p><strong>Exercise:</strong></p><ol><li>Set metronome to 80 BPM</li><li>Mute strings with left hand</li><li>Swing arm: down-up-down-up continuously</li><li>Contact strings on EVERY swing — down AND up</li><li>Feel the "1-and-2-and-3-and-4-and"</li></ol><p>This is the universal strumming pattern: D-U-D-U-D-U-D-U. Master this before adding any variation.</p>','https://www.youtube.com/embed/Vh_8Q8EU9O0',8,'metronome','{"bpm":80,"pattern":"down_up"}'),
      (7,'The 4 Essential Patterns','essential-patterns',2,'<p>Four strumming patterns that cover 90% of popular music:</p><p><strong>Pattern 1: All down</strong> — D, D, D, D (4/4, beat only)</p><p><strong>Pattern 2: Down-Up</strong> — D-U, D-U, D-U, D-U (8th notes)</p><p><strong>Pattern 3: The Pop Pattern</strong> — D, D-U, U-D, D-U (1-2-and, 3-and-4)</p><p><strong>Pattern 4: Highlife Pattern</strong> — D-U, D-, U-D, D-U (with a skip, syncopated feel)</p><p><strong>Practice each pattern:</strong></p><ol><li>Say the pattern out loud</li><li>Mute strings and strum the pattern</li><li>Add a chord (start with G)</li><li>Change chords every 4 beats while keeping the pattern steady</li></ol>','https://www.youtube.com/embed/pFtGN1BfqJg',12,'metronome','{"pattern":"all","bpm_range":[70,90,110]}'),
      (7,'Strumming with Songs','strumming-songs',3,'<p>Now apply your strumming patterns to actual songs. Different genres use different patterns:</p><p><strong>Gospel (slow):</strong> Pattern 1 (all down) — "Adom" by Ohemaa Mercy</p><p><strong>Highlife (medium):</strong> Pattern 3 (pop) — "Ewe" by King Promise</p><p><strong>Hiplife (fast):</strong> Pattern 2 (down-up) — "Ayayi" by Sarkodie</p><p><strong>Exercise:</strong> For each song above, identify the tempo and choose the right pattern. Practice for 3 minutes per song. The strumming arm should feel like a metronome — steady, independent, and tireless.</p>','https://www.youtube.com/embed/T5Bs1PG6bAQ',10,'song','{}'),
      (7,'Dynamic Strumming','dynamic-strumming',4,'<p>Great strumming isn''t just about rhythm — it''s about <strong>dynamics</strong> (loud vs soft).</p><p><strong>Accent exercise:</strong></p><ol><li>Strum G using Pattern 2 (D-U-D-U-D-U-D-U)</li><li>Play the down-strums LOUD, up-strums soft</li><li>Now reverse: down-strums soft, up-strums LOUD</li><li>Now accent beats 2 and 4 (the backbeat — key to highlife)</li></ol><p><strong>Ghanaian secret:</strong> In highlife guitar, the strumming hand often accents the OFF-beats (the "and" of each beat). This creates that signature syncopated bounce. Listen to "Ewe" by King Promise — hear how the guitar sits slightly behind the beat? That''s the highlife feel.</p>','https://www.youtube.com/embed/y6P2rbyIJOg',10,'metronome','{"pattern":"dynamic","bpm":90}'),
      (8,'A — The Bright Major','a-chord',1,'<p><strong>A major</strong> — a bright, open chord essential for Ghanaian gospel and highlife.</p><p><strong>Shape:</strong></p><ul><li>Index, middle, ring fingers all on fret 2</li><li>Index on string 4, middle on string 3, ring on string 2</li><li>Play strings 1-5 only. Don''t play string 6.</li></ul><p><strong>Alternative (easier for beginners):</strong> Use just index and middle — index on string 3 fret 2, middle on string 2 fret 2. This covers the essential notes.</p><p><strong>Practice:</strong> Drill A ↔ D (both are "fret 2 chords" — common anchor position). Target: 15+ changes in 60 seconds.</p>','https://www.youtube.com/embed/CjHxFmlq5FY',6,'chord','{"chord":"A","frets":[0,0,2,2,2,0]}'),
      (8,'E + Dm — Essential Additions','e-dm-chords',2,'<p><strong>E major</strong> — same shape as Am but shifted one string over.</p><ul><li>Index on string 3 fret 1, middle on string 5 fret 2, ring on string 4 fret 2</li><li>Play all 6 strings</li></ul><p><strong>Dm (D minor)</strong> — sad, soulful sound, essential for Ghanaian ballads.</p><ul><li>Index on string 1 fret 1, middle on string 3 fret 2, ring on string 2 fret 3</li><li>Play strings 1-4 only</li></ul><p><strong>Practice circuit:</strong> Am → E → Dm → Am. These are related chords in the key of A minor. Many Ghanaian songs use this exact progression.</p>','https://www.youtube.com/embed/D4Gj3xh9f4g',8,'chord','{"chords":["E","Dm"],"mode":"circuit"}'),
      (8,'B7 — The Highlife Favourite','b7-chord',3,'<p><strong>B7</strong> — this chord appears in countless Ghanaian highlife and gospel songs. It has a rich, full sound that resolves beautifully to E.</p><p><strong>Shape:</strong></p><ul><li>Index on string 4 fret 1</li><li>Middle on string 5 fret 2</li><li>Ring on string 3 fret 2</li><li>Pinky on string 1 fret 2</li><li>Play all 6 strings</li></ul><p><strong>Common progression:</strong> B7 → E → A (the II-V-I in the key of A). This is the backbone of Ghanaian gospel music.</p><p><strong>Drill:</strong> B7 ↔ E (the middle finger anchors on string 5 fret 2 — keep it there).</p>','https://www.youtube.com/embed/50F_OXMXatI',8,'chord','{"chord":"B7","frets":[0,2,1,2,0,2]}'),
      (8,'All 10 Chords Circuit','10-chord-circuit',4,'<p>You now know 10 open chords: Em, Am, G, C, D, A, E, Dm, B7, F (partial).</p><p><strong>The Grand Circuit:</strong> Practice each pair for 60 seconds. Record your scores.</p><ol><li>Em↔Am</li><li>Am↔G</li><li>G↔C</li><li>C↔D</li><li>D↔A</li><li>A↔E</li><li>E↔Dm</li><li>Dm↔B7</li><li>B7↔Em (close the circle!)</li></ol><p><strong>Your One-Minute Total is now out of 9 pairs.</strong> Track this number. By week 4, aim for 150+ total.</p>','https://www.youtube.com/embed/qvQdGaOn9Cg',12,'oneminute','{"pairs":["Em-Am","Am-G","G-C","C-D","D-A","A-E","E-Dm","Dm-B7","B7-Em"]}'),
      (9,'Ayayi — Sarkodie','ayayi',1,'<p><strong>Song:</strong> Ayayi — Sarkodie</p><p><strong>Chords:</strong> G, D, Em, C</p><p><strong>Progression:</strong> G → D → Em → C (repeat)</p><p>This is the I-V-vi-IV progression — the most common chord progression in ALL popular music. Once you learn this, you can play hundreds of songs.</p><p><strong>Strum pattern:</strong> Pop pattern (D, D-U, U-D, D-U) at 96 BPM</p><p><strong>Practice plan:</strong></p><ol><li>Silent transitions — G→D, D→Em, Em→C, C→G (5 min)</li><li>One strum per chord at 60 BPM (5 min)</li><li>Full strum pattern at 80 BPM (5 min)</li></ol>','https://www.youtube.com/embed/93n-4RqkFKA',15,'song','{"song_id":3,"chords":["G","D","Em","C"]}'),
      (9,'Ewe — King Promise','ewe',2,'<p><strong>Song:</strong> Ewe — King Promise</p><p><strong>Chords:</strong> G, D, Em, C (same as Ayayi!)</p><p><strong>Progression:</strong> Em → C → G → D (same chords, different order)</p><p>Notice how the SAME four chords can create completely different songs just by changing the order. This is the power of learning chords — not songs.</p><p><strong>Highlife strum:</strong> D-U D- U-D D-U (syncopated, accenting the off-beats)</p><p><strong>Tip:</strong> Listen to the guitar carefully in the original recording. The highlife guitar plays short, choppy strums between the vocals. That''s the "chop" technique — quick muted strums that add texture.</p>','https://www.youtube.com/embed/0_MUHeq0tPg',15,'song','{"song_id":4,"chords":["G","D","Em","C"]}'),
      (9,'Adom — Ohemaa Mercy','adom',3,'<p><strong>Song:</strong> Adom — Ohemaa Mercy</p><p><strong>Chords:</strong> A, E, D</p><p><strong>Progression:</strong> A → E → D → A (I-V-IV-I in the key of A)</p><p>This slow gospel song lets you practice the A-E-D progression. At slow tempos (65 BPM), there''s nowhere to hide — every chord must ring clean.</p><p><strong>Practice strategy:</strong></p><ul><li>Play quarter notes (down only) at 60 BPM</li><li>Focus on the A→E transition — the ring finger goes from string 2 fret 2 to string 4 fret 2 while the index moves from string 3 fret 2 to string 3 fret 1</li><li>Once clean, add the highlife-inspired down-up strum</li></ul>','https://www.youtube.com/embed/JMq5bmYEGT4',15,'song','{"song_id":5,"chords":["A","E","D"]}'),
      (9,'Building Your Repertoire','building-repertoire',4,'<p>A repertoire is a set of songs you can play from memory at any time. Building one is how you go from "learner" to "musician."</p><p><strong>Your current repertoire:</strong></p><ul><li>✅ Wish Me Well (2 chords)</li><li>✅ Ayayi (4 chords)</li><li>✅ Ewe (4 chords)</li><li>✅ Adom (3 chords)</li></ul><p><strong>Memory method (active recall):</strong></p><ol><li>Try to play each song WITHOUT looking at the chord chart</li><li>When you get stuck, check the chart</li><li>Try again from memory</li><li>Repeat daily until all 4 songs are memorised</li></ol><p><strong>Weekly challenge:</strong> Add one new Ghanaian song to your repertoire every week. Search online or ask a musician friend for suggestions.</p>','https://www.youtube.com/embed/kP0oXAfWxWg',8,'song','{"mode":"repertoire"}'),
      (10,'What is Tablature?','what-is-tablature',1,'<p>Tablature ("tab") is a simple notation system that shows you WHERE to put your fingers on the fretboard — no sheet music reading required.</p><p><strong>How tab works:</strong></p><pre>
e|---0---1---2---3---|
B|---0---1---2---3---|
G|---0---1---2---3---|
D|---0---1---2---3---|
A|---0---1---2---3---|
E|---0---1---2---3---|</pre><p>Each line = a string (e=1st, B=2nd, G=3rd, D=4th, A=5th, E=6th).</p><p>Numbers = fret number. 0 = open string.</p><p>Read left to right, play notes in order.</p><p><strong>Exercise:</strong> The tab above is a simple chromatic scale. Play it slowly — each note should ring clean before you move to the next.</p>','https://www.youtube.com/embed/iM7pE4Y8R_s',8,'fretboard','{"mode":"tab_reading"}'),
      (10,'Reading Chord Charts','reading-chord-charts',2,'<p>Chord charts are vertical diagrams showing the guitar neck.</p><p><strong>How to read a chord chart:</strong></p><ul><li>6 vertical lines = strings (E A D G B e, left to right)</li><li>Horizontal lines = frets</li><li>Dots = where to place your fingers</li><li>Numbers inside dots = which finger (1=index, 2=middle, 3=ring, 4=pinky)</li><li>"X" above a string = don''t play it</li><li>"O" above a string = play it open</li></ul><p><strong>Exercise:</strong> Find chord charts for all 10 chords you know. Read each one and place your fingers WITHOUT looking at the diagrams you memorised earlier. This builds chord chart fluency.</p>','https://www.youtube.com/embed/JTobO_tRpsA',6,'chord','{"mode":"charts"}'),
      (10,'Find Any Note on the Fretboard','find-any-note',3,'<p>Once you know the open string names and the musical alphabet, you can find ANY note on the fretboard.</p><p><strong>The formula:</strong></p><ul><li>Each fret = one semitone (half step)</li><li>Musical alphabet: A, A#, B, C, C#, D, D#, E, F, F#, G, G# (then back to A)</li><li>Exceptions (no sharp between): B→C, E→F</li></ul><p><strong>Exercise:</strong> Find every "A" on your fretboard.</p><ol><li>String 5 open = A</li><li>String 6 fret 5 = A</li><li>String 4 fret 7 = A</li><li>String 3 fret 2 = A</li><li>String 2 fret 10 = A</li><li>String 1 fret 5 = A</li></ol><p>Do this for C, D, E, G. This exercise teaches you the fretboard layout faster than any other method.</p>','https://www.youtube.com/embed/5S8BOiB9e6g',10,'fretboard','{"mode":"note_finder"}'),
      (10,'Tab Reading Practice','tab-reading-practice',4,'<p>Let''s read a real musical phrase in tablature — the opening of a Ghanaian highlife melody.</p><pre>
e|-----------------|-----------------|
B|-----------------|-----------------|
G|-----------0-2---|-----0-2-4-2-0---|
D|-------0-2-------|-0-2-------------|
A|-----------------|-----------------|
E|-----------------|-----------------|</pre><p>This is a classic highlife guitar phrase in G major. Play it slowly with a metronome at 60 BPM.</p><p><strong>Interpretation:</strong> The melody moves between the D and G strings (strings 4 and 3). Open D → fret 2 (E) → open G → fret 2 (A) → fret 4 (B) → back down.</p><p>This kind of melodic phrase is the foundation of highlife lead guitar. Once you can read and play this, you can start learning highlife solos from tabs online.</p>','https://www.youtube.com/embed/RnqYMqXQ0ac',10,'fretboard','{"mode":"tab_practice"}'),
      (11,'A Minor Pentatonic — Shape 1','pentatonic-shape-1',1,'<p>The pentatonic scale has only 5 notes (penta=5, tonic=tone). It''s the most important scale in guitar music — used in rock, blues, highlife, and hiplife.</p><p><strong>A minor pentatonic, first position:</strong></p><pre>
e|---5---8---|
B|---5---8---|
G|---5---7---|
D|---5---7---|
A|---5---7---|
E|---5---8---|</pre><p>All notes are A (root), C (minor 3rd), D (4th), E (5th), G (minor 7th).</p><p><strong>Practice:</strong> Play this shape ascending and descending at 60 BPM. Each note must ring CLEAN. Use alternate picking: down-up-down-up.</p>','https://www.youtube.com/embed/xHsp3FpZgFY',10,'fretboard','{"mode":"pentatonic","key":"Am","shape":1,"bpm":60}'),
      (11,'Pentatonic — Descending & Sequences','pentatonic-descending',2,'<p>Most beginners only practice ascending (going up). <strong>Descending is equally important and sounds more musical.</strong></p><p><strong>Ascending then descending:</strong></p><p>Play the full shape up and down without stopping. Use a metronome. Start at 60 BPM, go up to 80 BPM, then 100 BPM.</p><p><strong>Sequence 1 (3-notes):</strong> Play groups of 3 ascending notes, then move up one note and repeat.</p><ul><li>5-5-5, 5-5-7, 5-7-7, 7-7-7 (on string 6)</li><li>Then move to string 5: 5-5-5, 5-5-7, 5-7-7, 7-7-7</li></ul><p>This builds the finger coordination for actual solos, where notes aren''t played in simple ascending order.</p>','https://www.youtube.com/embed/fwkHExVxgAY',10,'fretboard','{"mode":"pentatonic","key":"Am","type":"descending","bpm":80}'),
      (11,'Simple Pentatonic Licks','pentatonic-licks',3,'<p>Now use your pentatonic scale to play actual musical phrases (licks).</p><p><strong>Lick 1 (Highlife-style):</strong></p><pre>
e|-------------------------|
B|-------------------------|
G|---7---5---4---2---0-----|
D|-------------------------|
A|-------------------------|
E|-------------------------|</pre><p>Play on string 3 (G string): G→E→D→C→A (the first 5 notes of the pentatonic scale descending).</p><p><strong>Lick 2 (Call and response):</strong></p><pre>
e|-8-8-8---5-5-5---8-5-8---|
B|-------------------------|
G|-------------------------|
D|-------------------------|
A|-------------------------|
E|-------------------------|</pre><p>This mimics the highlife call-and-response vocal style on the guitar. Play it with feeling — not just correct notes, but the RIGHT rhythm.</p>','https://www.youtube.com/embed/gg8GpQx27hU',10,'fretboard','{"mode":"pentatonic","type":"licks"}'),
      (11,'Pentatonic Jam Session','pentatonic-jam',4,'<p>Time to jam! Use the A minor pentatonic scale to improvise over a backing track.</p><p><strong>Rules of the jam:</strong></p><ol><li>Start with just the root note A — play it on different strings</li><li>Add one more note (C or E) — play just two notes for the whole jam</li><li>Add a third note</li><li>Gradually use all 5 notes</li></ol><p><strong>Pro tip from Ericsson:</strong> The best musicians sound great playing just 2-3 notes. Restriction forces creativity. Try playing a 60-second solo using ONLY the notes A and E. Then add C. The fewer notes you use, the more musical your playing becomes.</p><p><strong>Backing track:</strong> Use the embedded YouTube video below — it''s an A minor backing track at 80 BPM. Perfect for pentatonic practice.</p>','https://www.youtube.com/embed/4m_R17WWqkE',12,'fretboard','{"mode":"pentatonic","type":"jam","bpm":80}'),
      (12,'Thumb-Lead Fingerpicking Pattern','thumb-lead',1,'<p>Fingerpicking is where your right hand finally gets its own workout.</p><p><strong>The basic position:</strong></p><ul><li>Thumb (p) — controls strings 4, 5, 6 (the bass strings)</li><li>Index (i) — string 3</li><li>Middle (m) — string 2</li><li>Ring (a) — string 1</li></ul><p><strong>Pattern 1: Thumb-Lead (Travis Picking):</strong></p><p>The thumb plays a steady bass pattern on beats 1, 2, 3, 4. The fingers fill in between. This is the most important fingerpicking pattern.</p><p>Hold Em. Thumb plays string 5 on beats 1,2,3,4. Index+middle+ring play strings 3,2,1 together on the "and" of each beat.</p><p>Think of it as: <strong>THUMB (beat) — fingers (&) — THUMB — fingers — THUMB — fingers — THUMB — fingers</strong></p>','https://www.youtube.com/embed/YdA7b5B6BgU',10,'practice','{"type":"fingerpicking","pattern":"thumb_lead"}'),
      (12,'Basic Fingerpicking Patterns','fingerpicking-patterns',2,'<p><strong>Pattern 2: PIMA Arpeggio</strong></p><p>P = thumb, I = index, M = middle, A = ring. Play each finger one at a time in order:</p><p>Thumb (string 5) → Index (string 3) → Middle (string 2) → Ring (string 1)</p><p>Repeat. Speed up gradually. Then try it on different chord shapes.</p><p><strong>Pattern 3: The Gospel Ballad</strong></p><p>Thumb plays string 5 on beat 1. Index+Middle+Ring together on strings 3,2,1 on beat 2. Thumb on beat 3. Three fingers on beat 4.</p><p>This pattern is used extensively in Ghanaian gospel music (Joe Mettle, Ohemaa Mercy). Practice it on G, C, and D chords.</p><p><strong>Pattern 4: Highlife Fingerstyle</strong></p><p>Thumb alternates between strings 5 and 4. Fingers pick a melody on strings 1-3. This is more advanced — take it slow and build up.</p>','https://www.youtube.com/embed/iDnW0SpC0q8',12,'practice','{"type":"fingerpicking","pattern":"pima"}'),
      (12,'Fingerstyle Ghanaian Melody','fingerstyle-melody',3,'<p>Here''s a simple fingerstyle arrangement of a Ghanaian folk melody:</p><pre>
  Em              Am              Em              Am
e|----0----0----|----1----1----|----0----0----|----1----1----|
B|----0----0----|----1----1----|----0----0----|----1----1----|
G|----0----0----|----2----2----|----0----0----|----2----2----|
D|----2----2----|----2----2----|----2----2----|----2----2----|
A|----2----2----|----0----0----|----2----2----|----0----0----|
E|----0----0----|--------------|----0----0----|--------------|</pre><p>The thumb plays the bass note (lowest note of each chord) on the beat. The index+middle+ring pluck the other strings simultaneously.</p><p><strong>Tip:</strong> Keep your thumb relaxed. Many beginners tense up their thumb — this makes the pattern sound stiff. Think of your thumb as a gentle heartbeat.</p>','https://www.youtube.com/embed/0XB64TzCwW4',15,'practice','{"type":"fingerpicking","pattern":"melody"}'),
      (12,'Fingerpicking + Strumming Hybrid','hybrid-picking',4,'<p>Advanced technique: combine fingerpicking with occasional strums for a fuller sound.</p><p><strong>The hybrid technique:</strong></p><ul><li>Fingers pick individual strings for the verse</li><li>Switch to strumming for the chorus</li><li>The transition should be seamless — no pause between picking and strumming</li></ul><p><strong>Exercise:</strong> Play the fingerstyle pattern from the previous lesson. At the 4th bar, instead of fingerpicking, strum the chord once. Then go back to fingerpicking. This verse-chorus dynamic is the secret to professional-sounding guitar.</p><p>Try this with "Ewe" by King Promise — fingerpick the verses, strum the chorus.</p>','https://www.youtube.com/embed/MjH4LYgKJ3E',10,'practice','{"type":"hybrid"}'),
      (13,'Partial Barre Chords','partial-barre',1,'<p>Barre chords are the #1 reason guitarists quit. The key is to start small and build strength gradually.</p><p><strong>What is a barre?</strong> Your index finger presses ALL strings at once, like a movable capo. Your other fingers form a chord shape.</p><p><strong>Partial barre F (easier start):</strong></p><ul><li>Index finger barres only strings 1-2 at fret 1</li><li>Middle finger on string 3 fret 2</li><li>Ring finger on string 4 fret 3</li><li>Don''t play strings 5 and 6</li></ul><p>This gives you an F major chord without the hard full barre. Practice this for 3 minutes daily for a week before attempting full barre chords.</p>','https://www.youtube.com/embed/2GUfXUBYH5Y',10,'chord','{"chord":"F_partial","mode":"barre"}'),
      (13,'Full F Barre Chord','full-f-barre',2,'<p>Now the full F barre chord — the most famous hurdle in guitar.</p><p><strong>Full F barre shape:</strong></p><ul><li>Index finger barres all 6 strings at fret 1</li><li>Middle finger on string 3 fret 2</li><li>Ring finger on string 5 fret 3</li><li>Pinky on string 4 fret 3</li></ul><p><strong>Expectation management:</strong> Your index finger is not strong enough yet. For the first week, aim for 3 clean notes, not all 6. After 2 weeks, you''ll get 4 clean notes. After 3-4 weeks, all 6 will ring.</p><p>This is NORMAL. Even professional guitarists remember this struggle. The difference between those who succeed and those who quit is simply: they kept trying for 4 weeks.</p><p><strong>Drill:</strong> Press the barre only (no other fingers). Strum each string individually. Adjust finger position until all 6 strings ring. Hold for 10 seconds. Release. Repeat 10 times.</p>','https://www.youtube.com/embed/Afs1cK4L4iI',12,'chord','{"chord":"F","mode":"barre"}'),
      (13,'Bm Barre Chord','bm-barre',3,'<p><strong>Bm (B minor)</strong> — the second essential barre chord, from the E minor shape moved up.</p><p><strong>Shape:</strong> Em shape moved up 2 frets. Index barres fret 2 across all 6 strings.</p><ul><li>Index barres at fret 2</li><li>Middle on string 2 fret 3</li><li>Ring on string 4 fret 4</li><li>Pinky on string 3 fret 4</li></ul><p><strong>Tip:</strong> Your index finger should be slightly turned (thumbnail pointing up) so the bony edge presses the strings — not the soft pad. This gives you more pressure with less effort.</p><p><strong>Practice:</strong> 3 minutes of barre-only hold, then 5 minutes of Bm ↔ A transitions (both barre chords in the same position).</p>','https://www.youtube.com/embed/xV6TckuVVuA',12,'chord','{"chord":"Bm","mode":"barre"}'),
      (13,'Barre Chord Progressions','barre-progressions',4,'<p>Now use barre chords in real musical progressions.</p><p><strong>Progression 1 (Ghanaian Gospel):</strong> F → Bb → C → F</p><p>F barre at fret 1, Bb barre at fret 1 (A shape), C barre at fret 3 (A shape). This is the I-IV-V in F major — very common in Ghanaian gospel.</p><p><strong>Progression 2 (Highlife):</strong> Bm → A → G → F#m</p><p>All barre chords. Bm (fret 2, Em shape), A (fret 5, Em shape), G (fret 3, E shape), F#m (fret 2, Em shape).</p><p><strong>Practice strategy:</strong> Play each progression for 2 minutes. Don''t worry about strumming — just focus on getting ALL notes in each barre chord to ring clean before moving to the next. Speed comes later.</p>','https://www.youtube.com/embed/y4eblNTojQ0',10,'oneminute','{"pairs":["F-Bb","Bb-C","C-F","Bm-A","A-G","G-F#m"]}'),
      (14,'Highlife Guitar Style','highlife-style',1,'<p>Highlife guitar is a distinct West African style. It''s characterised by:</p><ul><li><strong>The "Chop"</strong> — short, percussive muted strums between chord changes</li><li><strong>Arpeggiated chords</strong> — picking chord tones individually rather than strumming</li><li><strong>Call and response</strong> — the guitar ''answers'' the vocalist</li><li><strong>Syncopation</strong> — the guitar sits slightly behind the beat</li></ul><p><strong>Exercise 1: The Chop</strong></p><p>Hold G chord. Strum all strings but immediately release pressure with your left hand so the strings mute. The result is a percussive "chk" sound. Do this on beats 2 and 4 of each measure.</p><p><strong>Exercise 2: Highlife Arpeggio</strong></p><p>Instead of strumming G, pick the strings individually: String 6 (G root) → String 4 (D) → String 3 (G) → String 2 (B). This arpeggio pattern IS the highlife guitar sound.</p>','https://www.youtube.com/embed/CX-8LM-gNss',12,'practice','{"type":"highlife","mode":"chop"}'),
      (14,'Ebo Taylor Style Phrasing','ebo-taylor',2,'<p>Ebo Taylor is Ghana''s greatest highlife guitarist. His phrasing is fluid, melodic, and unmistakably Ghanaian.</p><p><strong>Ebo''s signature technique:</strong> He plays short, repeating melodic patterns on the high strings (1-3) while the bass and percussion hold the rhythm. Think of it as a "melodic loop" that cycles every 2 or 4 bars.</p><p><strong>Ebo-style phrase:</strong></p><pre>
G (I)
e|-------------------------|
B|-------------------------|
G|-----0---2---4---2---0---|
D|---2---------------------|
A|-------------------------|
E|-------------------------|</pre><p>Play this over a G chord. This is a classic Ebo Taylor-style phrase — simple, melodic, and perfectly timed. Practice it until it feels like breathing.</p>','https://www.youtube.com/embed/pt9c5BpYHF0',15,'practice','{"type":"highlife","mode":"ebotaylor"}'),
      (14,'Amakye Dede Rhythm Guitar','amakye-dede',3,'<p>Amakye Dede''s guitarists use a driving, rhythmic style that propels the song forward.</p><p><strong>The Amakye Dede strum:</strong></p><p>A constant D-U-D-U pattern with ACCENTS on the up-strums. This creates a forward momentum that makes people dance.</p><p><strong>Progression in G:</strong></p><p>G (2 beats) → C (2 beats) → D (2 beats) → G (2 beats) → repeat</p><p>Strum D-U-D-U continuously. The up-strums should be slightly LOUDER than the down-strums. This reverse accent is the secret to the highlife drive.</p><p><strong>Tip:</strong> Keep your right hand moving ALWAYS — even on rests, your hand should continue the pendulum motion, just without touching the strings. This keeps you locked in the rhythm.</p>','https://www.youtube.com/embed/la8arO9BcO0',12,'practice','{"type":"highlife","mode":"amakye"}'),
      (14,'Write Your Own Highlife Progression','write-highlife',4,'<p>Now it''s your turn to create. Use the tools you''ve learned to write an original highlife chord progression and rhythm part.</p><p><strong>Your assignment:</strong></p><ol><li>Choose 3-4 chords from: G, C, D, Em, Am, B7, F</li><li>Write a 4-bar progression using the I-IV-V or I-V-vi-IV pattern</li><li>Add a highlife strum pattern (syncopated, accent off-beats)</li><li>Add one "chop" (muted strum) per bar</li><li>Record yourself playing it — even a phone recording</li><li>Share it with the community (optional, but recommended)</li></ol><p><strong>Why this matters:</strong> Creating your own music is the ultimate goal of all this practice. You started 14 modules ago not knowing how to hold a guitar. Now you''re writing your own music. That''s transformation.</p>','https://www.youtube.com/embed/o0jG6ofQ0rM',15,'practice','{"type":"highlife","mode":"composition"}'),
      (15,'Choose Your Mastery Song','choose-mastery-song',1,'<p>This module is different — you choose ONE song to master completely. Not just "play through it" but MASTER it.</p><p><strong>Mastery criteria:</strong></p><ul><li>Play the song from memory (no chord chart)</li><li>Play in time with the original recording at full tempo</li><li>All chord transitions are clean</li><li>Strum pattern is consistent and dynamic</li><li>You can play it for someone else without stopping</li></ul><p><strong>Suggested songs (Ghanaian):</strong></p><ul><li>"Ayayi" by Sarkodie (4 chords, medium tempo) — best for intermediate</li><li>"Ewe" by King Promise (4 chords, mid-tempo highlife) — intermediate</li><li>"Grace" by Joe Mettle (barre chords, slow) — advanced</li><li>Any song of your choice using chords you know</li></ul><p>You have the entire week to master this ONE song. Quality over quantity.</p>','https://www.youtube.com/embed/UMXxv7dmmeI',5,'song','{"mode":"mastery_select"}'),
      (15,'Song Breakdown Method','song-breakdown',2,'<p>Here''s how to break down ANY song for rapid mastery:</p><p><strong>Step 1 — Structure map:</strong> Listen to the song and write down the structure: Intro → Verse → Chorus → Verse → Chorus → Bridge → Chorus → Outro</p><p><strong>Step 2 — Section isolation:</strong> For each section, identify the chords and strum pattern. Write them down.</p><p><strong>Step 3 — The hard bar:</strong> Find the ONE bar in the song that you stumble on. Isolate it. Play it 20 times perfectly. Rest. Play it 20 more times. This is deliberate practice in action.</p><p><strong>Step 4 — Section linking:</strong> Once each section is solid, practice the transitions between sections. The verse→chorus transition is usually the hardest — the feel often changes.</p><p><strong>Step 5 — Full run-through:</strong> Play the entire song 3 times without stopping, regardless of mistakes. Record the third attempt.</p>','https://www.youtube.com/embed/X0V1SU-BT3c',15,'song','{"mode":"mastery_breakdown"}'),
      (15,'Slow Practice — The Secret Weapon','slow-practice',3,'<p>Here''s a counter-intuitive truth: <strong>the fastest way to play fast is to practice slow.</strong></p><p><strong>The 50% rule:</strong></p><p>Take the tempo of the song and cut it in half. Practice at HALF tempo for 10 minutes. You will be bored. You will want to speed up. DON''T.</p><p>At half tempo, you have time to:</p><ul><li>Hear each note clearly before playing it</li><li>See your finger placement before pressing</li><li>Feel the rhythm internally before strumming</li><li>Notice tension and release it</li></ul><p><strong>Progression:</strong> 50% tempo for 3 days → 75% for 2 days → 90% for 1 day → Full tempo on the final day. This gradual approach builds reliability into your muscle memory that "full tempo from day 1" never achieves.</p>','https://www.youtube.com/embed/4NKwNWJF_28',12,'song','{"mode":"mastery_slow"}'),
      (15,'Performance & Recording','performance-recording',4,'<p>This is your final assignment. Record yourself playing the song from start to finish.</p><p><strong>Recording tips:</strong></p><ul><li>Use your phone — good enough quality</li><li>Play along with the original song (headphones in one ear, guitar audible)</li><li>If you make a mistake, keep going — don''t stop and restart</li><li>The goal is NOT perfection — it''s COMPLETION</li></ul><p><strong>After recording:</strong> Listen back. Make notes on 2 things you did well and 1 thing to improve. This self-assessment is the hallmark of a deliberate practitioner.</p><p><strong>Certificate:</strong> Once you''ve submitted your recording, you''re eligible for the Gideon Guitar Method Certificate of Completion. Contact us to receive it.</p>','https://www.youtube.com/embed/51rW_KFmyec',20,'song','{"mode":"mastery_record"}'),
      (16,'Real-Time Pitch Detection','pitch-detection',1,'<p>Welcome to Performance Mode! This module uses your device''s microphone to detect what you play in real time and score your accuracy.</p><p><strong>How it works:</strong></p><ol><li>Grant microphone access when prompted</li><li>Play single notes on your guitar</li><li>The app detects the pitch and displays the note name</li><li>If you''re playing the CORRECT note (from the exercise), you gain score</li><li>Wrong notes = no score. Missed notes = lost streak.</li></ol><p><strong>Warning:</strong> Pitch detection works best in a quiet room. It needs to hear YOUR guitar, not the TV or conversations. For the most accurate detection, use an electric guitar connected to an audio interface, or play acoustic near your device''s microphone.</p><p><strong>Start with the tuner page first</strong> to calibrate your setup. Then come back here for scored exercises.</p>','https://www.youtube.com/embed/3I8CJj7rZxk',8,'tuner','{"mode":"intro"}'),
      (16,'Pitch Accuracy Challenge','pitch-accuracy',2,'<p>Your first scored challenge: play the correct notes as they appear on screen.</p><p><strong>How it works:</strong></p><ol><li>A note name appears on screen (e.g., "Play: E")</li><li>Find and play that note on your guitar</li><li>The app detects whether you played the right note</li><li>You have 3 seconds per note</li><li>10 notes per round. Score out of 100.</li></ol><p><strong>Notes in this challenge:</strong> E, A, D, G, B, e (the open strings — you know these!)</p><p><strong>Target scores:</strong></p><ul><li>40-60: Getting started — focus on finding notes faster</li><li>60-80: Solid — you know the open strings</li><li>80-100: Mastery — you can find notes instantly</li></ul><p>Repeat this challenge daily. Your score should improve as your note recognition speeds up.</p>','https://www.youtube.com/embed/_LwDcgWVKPA',8,'tuner','{"mode":"accuracy","notes":["E2","A2","D3","G3","B3","E4"],"timeout":3}'),
      (16,'Strum Pattern Accuracy','strum-accuracy',3,'<p>Now we test your strumming timing. The app detects whether your strums land on the beat.</p><p><strong>The exercise:</strong></p><ol><li>Metronome starts at 80 BPM</li><li>The screen shows a strum pattern: D-D-U-D-U</li><li>You strum along while holding a G chord</li><li>The app detects your strum timing</li><li>Green = on beat, Yellow = slightly off, Red = missed</li></ol><p><strong>Difficulty levels:</strong></p><ul><li>Level 1: Down-strums only, 60 BPM</li><li>Level 2: Down-Up, 80 BPM</li><li>Level 3: Pop Pattern (D, D-U, U-D, D-U), 80 BPM</li><li>Level 4: Highlife syncopated, 100 BPM</li></ul><p>Your score is calculated as: (on-time strums / total strums) × 100. Aim for 90%+.</p>','https://www.youtube.com/embed/wBf_ETTJLGs',12,'practice','{"mode":"strum_accuracy","bpm":80,"levels":4}'),
      (16,'Full Song Performance Mode','full-performance',4,'<p>This is the final challenge of the Gideon Guitar Method. Play a full song while the app scores every note and chord.</p><p><strong>How it works:</strong></p><ol><li>Choose a song from your repertoire or the song library</li><li>The app shows the chord progression in real time, scrolling like karaoke</li><li>You play along — the app detects your chords and timing</li><li>Each correct chord (right notes + right timing) adds to your score</li><li>At the end: total accuracy %, timing score, and XP earned</li></ol><p><strong>Scoring:</strong></p><ul><li><strong>Note accuracy (50%):</strong> Are you playing the right chords?</li><li><strong>Timing accuracy (30%):</strong> Are you switching chords on time?</li><li><strong>Consistency (20%):</strong> Did you complete the song without stopping?</li></ul><p><strong>Final grade:</strong></p><ul><li>90-100%: Gold — you''re ready to perform live!</li><li>70-89%: Silver — solid player, keep refining</li><li>50-69%: Bronze — good foundation, more practice needed</li></ul><p>This is the culmination of everything you''ve learned. From holding a guitar for the first time to playing a full song with real-time scoring — you''ve come an incredibly long way.</p>','https://www.youtube.com/embed/jDzSGWI7g2c',20,'practice','{"mode":"full_performance"}')`);

    seeds.push(`DELETE FROM guitar_achievements`);
    seeds.push(`INSERT INTO guitar_achievements (key,tier,name,description,icon,criteria) VALUES
      ('first_note','bronze','First Note','Played your first clean note','🎵','{"type":"lesson","lesson_id":1}'),
      ('first_chord','bronze','First Chord','Mastered Em — the easiest chord','🎸','{"type":"lesson","lesson_id":5}'),
      ('power_5','bronze','Power 5','Learned all 5 power chords (Em, Am, G, C, D)','💪','{"type":"module","module_id":3}'),
      ('speed_demon_15','bronze','Speed Demon (15)','15+ one-minute changes on a chord pair','⚡','{"type":"oneminute","score":15}'),
      ('first_song','bronze','First Song','Played your first complete song','🌟','{"type":"song","song_id":1}'),
      ('perfect_tune','bronze','Perfect Tune','Tuned your guitar using the tuner','🎯','{"type":"tuner","count":1}'),
      ('7_day_streak','silver','Week Warrior','7-day practice streak','🔥','{"type":"streak","days":7}'),
      ('speed_demon_25','silver','Speed Demon (25)','25+ one-minute changes','⚡','{"type":"oneminute","score":25}'),
      ('repertoire_3','silver','Growing Repertoire','3 songs memorised','📚','{"type":"repertoire","count":3}'),
      ('metronome_master','silver','Metronome Master','Played cleanly at 100+ BPM','⏱️','{"type":"bpm","bpm":100}'),
      ('ghanaian_player','silver','Ghanaian Player','Learned 3 Ghanaian songs','🇬🇭','{"type":"songs","ghanaian":3}'),
      ('14_day_streak','silver','Fortnight Warrior','14-day practice streak','🔥','{"type":"streak","days":14}'),
      ('speed_demon_35','silver','Speed Demon (35)','35+ one-minute changes (pro level!)','⚡','{"type":"oneminute","score":35}'),
      ('barre_warrior','gold','Barre Warrior','Played a clean F barre chord','🛡️','{"type":"module","module_id":13}'),
      ('pentatonic_pro','gold','Pentatonic Pro','Mastered the A minor pentatonic scale','🎼','{"type":"module","module_id":11}'),
      ('fingerpicker','gold','Fingerpicker','Completed the fingerpicking module','🤲','{"type":"module","module_id":12}'),
      ('highlife_guitarist','gold','Highlife Guitarist','Mastered highlife guitar style','🎶','{"type":"module","module_id":14}'),
      ('30_day_streak','gold','True Nation Builder','30-day practice streak','👑','{"type":"streak","days":30}'),
      ('song_mastery','gold','Song Master','Completed a full song mastery project','🏆','{"type":"module","module_id":15}'),
      ('certificate_eligible','gold','Gideon Graduate','Completed all 16 modules','🎓','{"type":"all_modules","count":16}')`);

    seeds.push(`DELETE FROM guitar_songs`);
    seeds.push(`INSERT INTO guitar_songs (title,artist,genre,chords,difficulty,min_module_id,youtube_url,chord_progression,lyrics_preview,ghanaian) VALUES
      ('Wish Me Well','Sarkodie','Hiplife','Em,Am',1,6,'https://www.youtube.com/embed/HnXo2LsYbMg','Em → Am','Wish me well, wish me well, make I dey go my way...',1),
      ('Adonai','Joe Mettle','Gospel','G,D',1,6,'https://www.youtube.com/embed/45iNJEfnG0M','G → D','Adonai, Adonai, we worship You...',1),
      ('Ayayi','Sarkodie','Hiplife','G,D,Em,C',2,9,'https://www.youtube.com/embed/93n-4RqkFKA','G → D → Em → C','Ayayi, me dey your side, nyame nhyira wo...',1),
      ('Ewe','King Promise','Highlife','G,D,Em,C',2,9,'https://www.youtube.com/embed/0_MUHeq0tPg','Em → C → G → D','Ewe, ewe, me de3 me da wo nsa...',1),
      ('Adom','Ohemaa Mercy','Gospel','A,E,D',1,9,'https://www.youtube.com/embed/JMq5bmYEGT4','A → E → D → A','Adom, adom, wo dom no so...',1),
      ('Onaapo','Bisa Kdei','Highlife','G,C,D,Em',2,9,'https://www.youtube.com/embed/tNZ3E8y5BCo','G → C → D → Em','Onaapo, me na me do wo...',1),
      ('Too Much','Kofi Kinaata','Hiplife','Am,F,G,C',2,9,'https://www.youtube.com/embed/H3Ys3rXs0eg','Am → F → G → C','Too much, too much, this thing too much...',1),
      ('Sore','KiDi','Afrobeats','Em,G,D,A',3,11,'https://www.youtube.com/embed/Zlx94hS0WnU','Em → G → D → A','Sore, sore, me do wo sore...',1),
      ('Dwom','Akwaboah','Highlife','Am,G,F,E',3,11,'https://www.youtube.com/embed/ccTBPyFKKpI','Am → G → F → E','Dwom, dwom, this dwom ye de...',1),
      ('Grace','Joe Mettle','Gospel','G,C,Em,D',2,13,'https://www.youtube.com/embed/8vMTir_Xsho','G → C → Em → D','Grace, grace, God''s grace...',1),
      ('Blessings','Akwaboah','Highlife','C,G,Am,F',2,9,'https://www.youtube.com/embed/Kz3W79b0Kmg','C → G → Am → F','Blessings, blessings, count your blessings...',1),
      ('Mansa','M.anifest','Hiplife','Em,C,G,D',3,11,'https://www.youtube.com/embed/p5fQj7TNTtE','Em → C → G → D','Mansa, you be gold, you be diamond...',1),
      ('Yesterday','Efya','Soul','G,Em,C,D',2,11,'https://www.youtube.com/embed/L1RBSGzVrTI','G → Em → C → D','Yesterday, all my troubles seemed so far away...',1),
      ('Down flat (Midi)','Ebo Taylor','Highlife','Am7,D7,Gmaj7,Cmaj7',3,14,'https://www.youtube.com/embed/U49E1he7RZc','Am7 → D7 → Gmaj7 → Cmaj7','Instrumental highlife groove...',1),
      ('Yellow Sisi','Patapaa','Hiplife','G,C,D',1,6,'https://www.youtube.com/embed/h0FvL0iKCWY','G → C → D','Yellow sisi, yellow yellow sisi...',1)`);

    for (const sql of seeds) { try { await db.prepare(sql).run(); } catch(e) { console.error('Seed:', e.message, e.stack); } }

    return new Response(JSON.stringify({ok:true, message:'Guitar tables ready', tables:['guitar_modules','guitar_lessons','guitar_exercises','guitar_songs','guitar_achievements','guitar_progress','guitar_practice_sessions','guitar_one_minute_records','guitar_user_stats','guitar_user_achievements','guitar_payments','guitar_tuner_history','guitar_waitlist','guitar_conversion_events']}), {headers:{'Content-Type':'application/json'}});
  } catch(e) {
    return new Response(JSON.stringify({error:e.message}), {status:500, headers:{'Content-Type':'application/json'}});
  }
}
